const logoUrl = process.env.EMAIL_BRAND_LOGO_URL || "https://miqueaslanguagesolutions.com/logo.png";
const supportEmail = process.env.EMAIL_SUPPORT_ADDRESS || "m.stubbs@miqueaslanguagesolutions.com";
const supportPhone = process.env.EMAIL_SUPPORT_PHONE || "(321) 379-8010";
const websiteUrl = "https://miqueaslanguagesolutions.com";

export function escapeEmailHtml(value) {
  return String(value || "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;");
}

export function brandedPortalEmail({ heading, intro, bodyText = "", details = [], buttonLabel = "Open MLS Portal", buttonUrl = "https://miqueaslanguagesolutions.com/portal", greeting = "Hello,", footerNote = "This message was sent from the secure MLS Portal." }) {
  const rows = details.filter(([, value]) => value !== null && value !== undefined && String(value).trim()).map(([label, value]) => `<tr><td style="padding:8px 14px 8px 0;font-size:13px;font-weight:700;color:#721100;vertical-align:top">${escapeEmailHtml(label)}</td><td style="padding:8px 0;font-size:13px;line-height:1.6;color:#51453f">${escapeEmailHtml(value).replaceAll("\n", "<br>")}</td></tr>`).join("");
  const text = [greeting, "", intro, "", bodyText, ...details.map(([label, value]) => `${label}: ${value}`), "", `${buttonLabel}: ${buttonUrl}`, "", footerNote, "", "Miqueas Language Solutions", "Bridging Perspectives. Delivering Understanding.", supportEmail, supportPhone, websiteUrl].filter(Boolean).join("\n");
  const body = bodyText ? `<div style="white-space:pre-wrap;font-size:15px;line-height:1.75;background:#fffaf5;border:1px solid #eadfd8;border-radius:16px;padding:18px">${escapeEmailHtml(bodyText)}</div>` : "";
  const detailTable = rows ? `<table role="presentation" width="100%" style="margin:20px 0;padding:12px 18px;border:1px solid #eadfd8;border-radius:16px;background:#fffaf5">${rows}</table>` : "";
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f7f3ef;font-family:Arial,sans-serif;color:#24130e"><div style="max-width:660px;margin:0 auto;padding:28px 14px"><div style="background:#fff;border-radius:24px 24px 0 0;padding:24px;text-align:center"><img src="${escapeEmailHtml(logoUrl)}" alt="Miqueas Language Solutions" width="230" style="display:inline-block;max-width:80%;height:auto"></div><div style="background:#24130e;color:#fff;padding:25px 28px;text-align:center"><div style="font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:#f6b34c">MLS Portal</div><h1 style="margin:10px 0 0;font-size:28px;line-height:1.25">${escapeEmailHtml(heading)}</h1></div><div style="background:#fff;padding:28px;border-radius:0 0 24px 24px;box-shadow:0 12px 40px rgba(36,19,14,.10)"><p style="font-size:16px;line-height:1.6;margin-top:0">${escapeEmailHtml(greeting)}</p><p style="font-size:15px;line-height:1.75;color:#51453f">${escapeEmailHtml(intro)}</p>${body}${detailTable}<p style="text-align:center;margin:28px 0"><a href="${escapeEmailHtml(buttonUrl)}" style="display:inline-block;background:#721100;color:#fff;text-decoration:none;font-weight:700;padding:14px 22px;border-radius:14px">${escapeEmailHtml(buttonLabel)}</a></p><div style="margin-top:28px;border-top:1px solid #eadfd8;padding-top:20px;text-align:center;font-size:12px;line-height:1.75;color:#6b625e"><strong style="color:#721100">Miqueas Language Solutions</strong><br>Bridging Perspectives. Delivering Understanding.<br><a href="mailto:${escapeEmailHtml(supportEmail)}" style="color:#721100">${escapeEmailHtml(supportEmail)}</a> · ${escapeEmailHtml(supportPhone)}<br><a href="${websiteUrl}" style="color:#721100">miqueaslanguagesolutions.com</a><p style="margin:12px 0 0;color:#8b817b">${escapeEmailHtml(footerNote)}</p></div></div></div></body></html>`;
  return { text, html };
}
